services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - rembg_cache:/root/.u2net
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
    env_file:
      - .env

volumes:
  rembg_cache: